######################################################################
# Automatically generated by qmake (3.0) Wed May 28 11:44:08 2014
######################################################################

QT += opengl widgets
CONFIG += c++11
QMAKE_CXXFLAGS += -W -Wall -g
TEMPLATE = app
TARGET = paint488
INCLUDEPATH += .

# Input
HEADERS += paintwindow.hpp paintcanvas.hpp algebra.hpp
SOURCES += main.cpp paintwindow.cpp paintcanvas.cpp algebra.cpp
